# Generated by Django 2.0.7 on 2018-11-08 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=1000)),
                ('number', models.IntegerField()),
                ('building', models.CharField(max_length=100)),
                ('door', models.CharField(max_length=100)),
                ('elevator', models.BooleanField()),
                ('terrace', models.BooleanField()),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('forklift', models.BooleanField()),
                ('forklift_type', models.CharField(max_length=200)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
        ),
        migrations.CreateModel(
            name='DownloadAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license', models.BooleanField()),
                ('license_type', models.CharField(max_length=400)),
                ('moving_date', models.DateField()),
                ('visiting_date', models.DateField()),
                ('confirmation', models.CharField(max_length=200)),
                ('address1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloadaddress_first_address', to='addresses.Address')),
                ('address2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloadaddress_second_address', to='addresses.Address')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
        ),
        migrations.CreateModel(
            name='LoadAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license', models.BooleanField()),
                ('license_type', models.CharField(max_length=400)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addresses.Address')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
        ),
    ]
