# Generated by Django 2.0.7 on 2018-09-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=400)),
                ('address', models.CharField(max_length=400)),
                ('city', models.CharField(max_length=200)),
            ],
        ),
    ]
