# Generated by Django 2.0.7 on 2018-11-08 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bedroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed', models.IntegerField()),
                ('wardrobe', models.IntegerField()),
                ('mirror', models.IntegerField()),
                ('commode', models.IntegerField()),
                ('bedsite_table', models.IntegerField()),
                ('chair', models.IntegerField()),
                ('cradle', models.IntegerField()),
                ('tv', models.IntegerField()),
                ('picture', models.IntegerField()),
                ('gym', models.IntegerField()),
                ('nest', models.IntegerField()),
                ('ark', models.IntegerField()),
                ('bridge', models.IntegerField()),
                ('desk', models.IntegerField()),
                ('rack', models.IntegerField()),
                ('shelves', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
                ('downloadAddress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addresses.DownloadAddress')),
                ('loadAddress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addresses.LoadAddress')),
            ],
        ),
        migrations.CreateModel(
            name='Dinningroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.IntegerField()),
                ('chair', models.IntegerField()),
                ('module', models.IntegerField()),
                ('wall', models.IntegerField()),
                ('entrance', models.IntegerField()),
                ('sofa', models.IntegerField()),
                ('center_table', models.IntegerField()),
                ('lamp', models.IntegerField()),
                ('showcase', models.IntegerField()),
                ('tv', models.IntegerField()),
                ('picture', models.IntegerField()),
                ('mirror', models.IntegerField()),
                ('low_furniture', models.IntegerField()),
                ('sideboard', models.IntegerField()),
                ('rack', models.IntegerField()),
                ('shelves', models.IntegerField()),
            ],
        ),
    ]
